// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-IMXBinBXj1RYKq_b31ndXImsQjt9Q4',
    appId: '1:886551786756:android:9e0389d15660e4eafa0c51',
    messagingSenderId: '886551786756',
    projectId: 'suqum-app',
    storageBucket: 'suqum-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZkXtKfmF8d9t6tPGNyD8t0Fl1It9woE',
    appId: '1:886551786756:ios:62644a40a89f2952fa0c51',
    messagingSenderId: '886551786756',
    projectId: 'suqum-app',
    storageBucket: 'suqum-app.appspot.com',
    androidClientId: '886551786756-dqp8sqdn21r0f2if48mf1jrgcm9hfhan.apps.googleusercontent.com',
    iosClientId: '886551786756-n0f1f5m5970t53pi9vd9ucsvcsisg7ej.apps.googleusercontent.com',
    iosBundleId: 'com.suqum.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDuHpMOnkXiTyBdB_-SZ4ToirZa6Bozw',
    appId: '1:886551786756:web:9697d7eafed916cdfa0c51',
    messagingSenderId: '886551786756',
    projectId: 'suqum-app',
    authDomain: 'suqum-app.firebaseapp.com',
    storageBucket: 'suqum-app.appspot.com',
    measurementId: 'G-WL38DWR5E3',
  );

}